// server/bancoDePalavras.js

const listaCompleta = [
    // --- VERBOS DE AÇÃO (ESSENCIAIS PARA REUNIÕES) ---
    { word: "Achieve", translation: "Alcançar/Realizar" },
    { word: "Address", translation: "Abordar (um problema)" },
    { word: "Advise", translation: "Aconselhar" },
    { word: "Analyze", translation: "Analisar" },
    { word: "Approve", translation: "Aprovar" },
    { word: "Assess", translation: "Avaliar" },
    { word: "Assign", translation: "Atribuir (tarefa)" },
    { word: "Avoid", translation: "Evitar" },
    { word: "Brainstorm", translation: "Discutir ideias" },
    { word: "Budget", translation: "Orçar" },
    { word: "Clarify", translation: "Esclarecer" },
    { word: "Collaborate", translation: "Colaborar" },
    { word: "Compare", translation: "Comparar" },
    { word: "Confirm", translation: "Confirmar" },
    { word: "Consider", translation: "Considerar" },
    { word: "Convince", translation: "Convencer" },
    { word: "Decrease", translation: "Diminuir" },
    { word: "Deliver", translation: "Entregar" },
    { word: "Develop", translation: "Desenvolver" },
    { word: "Discuss", translation: "Discutir" },
    { word: "Encourage", translation: "Encorajar" },
    { word: "Ensure", translation: "Garantir/Assegurar" },
    { word: "Establish", translation: "Estabelecer" },
    { word: "Estimate", translation: "Estimar" },
    { word: "Evaluate", translation: "Avaliar" },
    { word: "Expand", translation: "Expandir" },
    { word: "Expect", translation: "Esperar (expectativa)" },
    { word: "Explain", translation: "Explicar" },
    { word: "Facilitate", translation: "Facilitar" },
    { word: "Fix", translation: "Consertar" },
    { word: "Forecast", translation: "Prever" },
    { word: "Handle", translation: "Lidar com" },
    { word: "Hire", translation: "Contratar" },
    { word: "Improve", translation: "Melhorar" },
    { word: "Increase", translation: "Aumentar" },
    { word: "Inform", translation: "Informar" },
    { word: "Invest", translation: "Investir" },
    { word: "Join", translation: "Juntar-se/Entrar" },
    { word: "Launch", translation: "Lançar" },
    { word: "Lead", translation: "Liderar" },
    { word: "Manage", translation: "Gerenciar" },
    { word: "Measure", translation: "Medir" },
    { word: "Mention", translation: "Mencionar" },
    { word: "Negotiate", translation: "Negociar" },
    { word: "Organize", translation: "Organizar" },
    { word: "Participate", translation: "Participar" },
    { word: "Plan", translation: "Planejar" },
    { word: "Prepare", translation: "Preparar" },
    { word: "Prevent", translation: "Prevenir" },
    { word: "Prioritize", translation: "Priorizar" },
    { word: "Produce", translation: "Produzir" },
    { word: "Promote", translation: "Promover" },
    { word: "Propose", translation: "Propor" },
    { word: "Provide", translation: "Fornecer" },
    { word: "Purchase", translation: "Comprar/Adquirir" },
    { word: "Raise", translation: "Levantar (questão/dinheiro)" },
    { word: "Reach", translation: "Alcançar" },
    { word: "Receive", translation: "Receber" },
    { word: "Reduce", translation: "Reduzir" },
    { word: "Refuse", translation: "Recusar" },
    { word: "Reject", translation: "Rejeitar" },
    { word: "Remind", translation: "Lembrar (alguém)" },
    { word: "Remove", translation: "Remover" },
    { word: "Reply", translation: "Responder" },
    { word: "Report", translation: "Relatar" },
    { word: "Request", translation: "Solicitar" },
    { word: "Require", translation: "Exigir/Requerer" },
    { word: "Research", translation: "Pesquisar" },
    { word: "Resolve", translation: "Resolver" },
    { word: "Respond", translation: "Responder" },
    { word: "Review", translation: "Revisar" },
    { word: "Risk", translation: "Arriscar" },
    { word: "Schedule", translation: "Agendar" },
    { word: "Select", translation: "Selecionar" },
    { word: "Share", translation: "Compartilhar" },
    { word: "Solve", translation: "Resolver/Solucionar" },
    { word: "Suggest", translation: "Sugerir" },
    { word: "Support", translation: "Apoiar/Suportar" },
    { word: "Target", translation: "Visar/Alvejar" },
    { word: "Track", translation: "Rastrear/Acompanhar" },
    { word: "Update", translation: "Atualizar" },
    
    // --- SUBSTANTIVOS CORPORATIVOS (Business Nouns) ---
    { word: "Advantage", translation: "Vantagem" },
    { word: "Agreement", translation: "Acordo" },
    { word: "Asset", translation: "Ativo/Bem" },
    { word: "Background", translation: "Contexto/Fundo" },
    { word: "Benchmark", translation: "Referência comparativa" },
    { word: "Benefit", translation: "Benefício" },
    { word: "Brand", translation: "Marca" },
    { word: "Budget", translation: "Orçamento" },
    { word: "Campaign", translation: "Campanha" },
    { word: "Career", translation: "Carreira" },
    { word: "Challenge", translation: "Desafio" },
    { word: "Client", translation: "Cliente" },
    { word: "Competitor", translation: "Concorrente" },
    { word: "Contract", translation: "Contrato" },
    { word: "Cost", translation: "Custo" },
    { word: "Customer", translation: "Consumidor" },
    { word: "Deadline", translation: "Prazo final" },
    { word: "Deal", translation: "Acordo/Negócio" },
    { word: "Decision", translation: "Decisão" },
    { word: "Demand", translation: "Demanda" },
    { word: "Department", translation: "Departamento" },
    { word: "Development", translation: "Desenvolvimento" },
    { word: "Disadvantage", translation: "Desvantagem" },
    { word: "Employee", translation: "Funcionário" },
    { word: "Employer", translation: "Empregador" },
    { word: "Environment", translation: "Ambiente" },
    { word: "Equipment", translation: "Equipamento" },
    { word: "Expense", translation: "Despesa" },
    { word: "Experience", translation: "Experiência" },
    { word: "Feedback", translation: "Retorno/Opinião" },
    { word: "Goal", translation: "Meta" },
    { word: "Growth", translation: "Crescimento" },
    { word: "Income", translation: "Renda" },
    { word: "Increase", translation: "Aumento" },
    { word: "Industry", translation: "Indústria/Setor" },
    { word: "Interest", translation: "Interesse/Juros" },
    { word: "Interview", translation: "Entrevista" },
    { word: "Investment", translation: "Investimento" },
    { word: "Invoice", translation: "Fatura" },
    { word: "Issue", translation: "Problema/Questão" },
    { word: "Job", translation: "Emprego/Trabalho" },
    { word: "Knowledge", translation: "Conhecimento" },
    { word: "Leader", translation: "Líder" },
    { word: "Leadership", translation: "Liderança" },
    { word: "Loss", translation: "Perda/Prejuízo" },
    { word: "Management", translation: "Gestão" },
    { word: "Manager", translation: "Gerente" },
    { word: "Market", translation: "Mercado" },
    { word: "Marketing", translation: "Marketing" },
    { word: "Meeting", translation: "Reunião" },
    { word: "Member", translation: "Membro" },
    { word: "Method", translation: "Método" },
    { word: "Milestone", translation: "Marco importante" },
    { word: "Negotiation", translation: "Negociação" },
    { word: "Network", translation: "Rede de contatos" },
    { word: "Offer", translation: "Oferta" },
    { word: "Office", translation: "Escritório" },
    { word: "Opportunity", translation: "Oportunidade" },
    { word: "Option", translation: "Opção" },
    { word: "Order", translation: "Pedido" },
    { word: "Organization", translation: "Organização" },
    { word: "Outcome", translation: "Resultado/Desfecho" },
    { word: "Owner", translation: "Dono/Proprietário" },
    { word: "Partner", translation: "Parceiro/Sócio" },
    { word: "Partnership", translation: "Parceria" },
    { word: "Payment", translation: "Pagamento" },
    { word: "Performance", translation: "Desempenho" },
    { word: "Plan", translation: "Plano" },
    { word: "Policy", translation: "Política (normas)" },
    { word: "Position", translation: "Cargo/Posição" },
    { word: "Presentation", translation: "Apresentação" },
    { word: "Price", translation: "Preço" },
    { word: "Priority", translation: "Prioridade" },
    { word: "Problem", translation: "Problema" },
    { word: "Process", translation: "Processo" },
    { word: "Product", translation: "Produto" },
    { word: "Production", translation: "Produção" },
    { word: "Profit", translation: "Lucro" },
    { word: "Project", translation: "Projeto" },
    { word: "Promotion", translation: "Promoção" },
    { word: "Proposal", translation: "Proposta" },
    { word: "Purpose", translation: "Propósito" },
    { word: "Quality", translation: "Qualidade" },
    { word: "Quarter", translation: "Trimestre" },
    { word: "Range", translation: "Gama/Intervalo" },
    { word: "Rate", translation: "Taxa" },
    { word: "Reason", translation: "Razão" },
    { word: "Record", translation: "Registro" },
    { word: "Report", translation: "Relatório" },
    { word: "Requirement", translation: "Requisito" },
    { word: "Research", translation: "Pesquisa" },
    { word: "Resource", translation: "Recurso" },
    { word: "Response", translation: "Resposta" },
    { word: "Responsibility", translation: "Responsabilidade" },
    { word: "Result", translation: "Resultado" },
    { word: "Revenue", translation: "Receita" },
    { word: "Review", translation: "Revisão/Análise" },
    { word: "Risk", translation: "Risco" },
    { word: "Role", translation: "Papel/Função" },
    { word: "Salary", translation: "Salário" },
    { word: "Sale", translation: "Venda" },
    { word: "Schedule", translation: "Agenda/Cronograma" },
    { word: "Service", translation: "Serviço" },
    { word: "Share", translation: "Ação (bolsa)/Parte" },
    { word: "Shareholder", translation: "Acionista" },
    { word: "Skill", translation: "Habilidade" },
    { word: "Solution", translation: "Solução" },
    { word: "Source", translation: "Fonte" },
    { word: "Staff", translation: "Equipe/Pessoal" },
    { word: "Stage", translation: "Estágio/Fase" },
    { word: "Stakeholder", translation: "Parte interessada" },
    { word: "Standard", translation: "Padrão" },
    { word: "Statement", translation: "Declaração/Extrato" },
    { word: "Step", translation: "Passo" },
    { word: "Stock", translation: "Ação/Estoque" },
    { word: "Strategy", translation: "Estratégia" },
    { word: "Structure", translation: "Estrutura" },
    { word: "Success", translation: "Sucesso" },
    { word: "Supply", translation: "Suprimento/Fornecimento" },
    { word: "Support", translation: "Suporte" },
    { word: "System", translation: "Sistema" },
    { word: "Target", translation: "Alvo/Meta" },
    { word: "Task", translation: "Tarefa" },
    { word: "Tax", translation: "Imposto" },
    { word: "Team", translation: "Time" },
    { word: "Technology", translation: "Tecnologia" },
    { word: "Term", translation: "Termo/Prazo" },
    { word: "Tool", translation: "Ferramenta" },
    { word: "Trade", translation: "Comércio" },
    { word: "Training", translation: "Treinamento" },
    { word: "Trend", translation: "Tendência" },
    { word: "Value", translation: "Valor" },
    { word: "View", translation: "Visão/Opinião" },
    { word: "Wage", translation: "Salário (horista)" },
    { word: "Workforce", translation: "Força de trabalho" },
    
    // --- TECH & ENGENHARIA (Sua Área) ---
    { word: "Agile", translation: "Ágil (Metodologia)" },
    { word: "Algorithm", translation: "Algoritmo" },
    { word: "API", translation: "Interface de Programação" },
    { word: "Application", translation: "Aplicativo" },
    { word: "Architecture", translation: "Arquitetura" },
    { word: "Automation", translation: "Automação" },
    { word: "Backlog", translation: "Lista de pendências" },
    { word: "Backup", translation: "Cópia de segurança" },
    { word: "Bandwidth", translation: "Largura de banda" },
    { word: "Bug", translation: "Falha/Erro no código" },
    { word: "Cache", translation: "Cache (memória rápida)" },
    { word: "Cloud", translation: "Nuvem" },
    { word: "Code", translation: "Código" },
    { word: "Commit", translation: "Commit (Salvar no Git)" },
    { word: "Compilation", translation: "Compilação" },
    { word: "Component", translation: "Componente" },
    { word: "Configuration", translation: "Configuração" },
    { word: "Connection", translation: "Conexão" },
    { word: "Console", translation: "Console/Terminal" },
    { word: "Content", translation: "Conteúdo" },
    { word: "Cookie", translation: "Cookie (Dados de navegação)" },
    { word: "Core", translation: "Núcleo/Central" },
    { word: "Cybersecurity", translation: "Cibersegurança" },
    { word: "Dashboard", translation: "Painel de controle" },
    { word: "Data", translation: "Dados" },
    { word: "Database", translation: "Banco de dados" },
    { word: "Debug", translation: "Depurar" },
    { word: "Deploy", translation: "Implantar" },
    { word: "Device", translation: "Dispositivo" },
    { word: "Developer", translation: "Desenvolvedor" },
    { word: "Documentation", translation: "Documentação" },
    { word: "Domain", translation: "Domínio" },
    { word: "Driver", translation: "Driver (Controlador)" },
    { word: "Element", translation: "Elemento" },
    { word: "Encryption", translation: "Criptografia" },
    { word: "Engine", translation: "Motor (de software)" },
    { word: "Environment", translation: "Ambiente (Dev/Prod)" },
    { word: "Error", translation: "Erro" },
    { word: "Feature", translation: "Funcionalidade" },
    { word: "Field", translation: "Campo (de dado)" },
    { word: "File", translation: "Arquivo" },
    { word: "Firewall", translation: "Firewall (Proteção de rede)" },
    { word: "Framework", translation: "Framework (Estrutura)" },
    { word: "Function", translation: "Função" },
    { word: "Gateway", translation: "Gateway (Porta de entrada)" },
    { word: "Hardware", translation: "Hardware (Parte física)" },
    { word: "Host", translation: "Hospedeiro/Servidor" },
    { word: "Icon", translation: "Ícone" },
    { word: "Image", translation: "Imagem" },
    { word: "Implementation", translation: "Implementação" },
    { word: "Index", translation: "Índice" },
    { word: "Infrastructure", translation: "Infraestrutura" },
    { word: "Input", translation: "Entrada (dados)" },
    { word: "Installation", translation: "Instalação" },
    { word: "Integration", translation: "Integração" },
    { word: "Interface", translation: "Interface" },
    { word: "Internet", translation: "Internet" },
    { word: "Issue", translation: "Problema (Ticket)" },
    { word: "Iteration", translation: "Iteração (Ciclo)" },
    { word: "Kernel", translation: "Kernel (Núcleo do SO)" },
    { word: "Key", translation: "Chave (Senha/API)" },
    { word: "Keyboard", translation: "Teclado" },
    { word: "Language", translation: "Linguagem" },
    { word: "Laptop", translation: "Notebook" },
    { word: "Latency", translation: "Latência (Atraso)" },
    { word: "Layer", translation: "Camada" },
    { word: "Layout", translation: "Layout (Visual)" },
    { word: "Library", translation: "Biblioteca (Código)" },
    { word: "License", translation: "Licença" },
    { word: "Link", translation: "Link/Elo" },
    { word: "Linux", translation: "Linux (Sistema Operacional)" },
    { word: "Load", translation: "Carga/Carregamento" },
    { word: "Log", translation: "Registro de eventos" },
    { word: "Login", translation: "Login (Acesso)" },
    { word: "Loop", translation: "Loop (Repetição)" },
    { word: "Machine", translation: "Máquina" },
    { word: "Maintenance", translation: "Manutenção" },
    { word: "Malware", translation: "Malware (Software malicioso)" },
    { word: "Memory", translation: "Memória" },
    { word: "Menu", translation: "Menu" },
    { word: "Message", translation: "Mensagem" },
    { word: "Method", translation: "Método" },
    { word: "Mode", translation: "Modo" },
    { word: "Model", translation: "Modelo" },
    { word: "Module", translation: "Módulo" },
    { word: "Monitor", translation: "Monitor" },
    { word: "Mouse", translation: "Mouse" },
    { word: "Network", translation: "Rede" },
    { word: "Node", translation: "Nó (de rede ou Node.js)" },
    { word: "Object", translation: "Objeto" },
    { word: "Offline", translation: "Offline (Desconectado)" },
    { word: "Online", translation: "Online (Conectado)" },
    { word: "Open Source", translation: "Código Aberto" },
    { word: "Operating System", translation: "Sistema Operacional" },
    { word: "Operation", translation: "Operação" },
    { word: "Option", translation: "Opção" },
    { word: "Output", translation: "Saída (dados)" },
    { word: "Package", translation: "Pacote" },
    { word: "Page", translation: "Página" },
    { word: "Parameter", translation: "Parâmetro" },
    { word: "Password", translation: "Senha" },
    { word: "Patch", translation: "Correção (Patch)" },
    { word: "Path", translation: "Caminho (Diretório)" },
    { word: "Performance", translation: "Desempenho" },
    { word: "Permission", translation: "Permissão" },
    { word: "Platform", translation: "Plataforma" },
    { word: "Plugin", translation: "Plugin (Extensão)" },
    { word: "Port", translation: "Porta (Rede)" },
    { word: "Portal", translation: "Portal" },
    { word: "Privacy", translation: "Privacidade" },
    { word: "Process", translation: "Processo" },
    { word: "Processor", translation: "Processador" },
    { word: "Program", translation: "Programa" },
    { word: "Programming", translation: "Programação" },
    { word: "Project", translation: "Projeto" },
    { word: "Protocol", translation: "Protocolo" },
    { word: "Prototype", translation: "Protótipo" },
    { word: "Provider", translation: "Provedor" },
    { word: "Query", translation: "Consulta (Banco de dados)" },
    { word: "Queue", translation: "Fila" },
    { word: "RAM", translation: "Memória RAM" },
    { word: "Recovery", translation: "Recuperação" },
    { word: "Release", translation: "Lançamento (Versão)" },
    { word: "Remote", translation: "Remoto" },
    { word: "Repository", translation: "Repositório" },
    { word: "Requirement", translation: "Requisito" },
    { word: "Resolution", translation: "Resolução" },
    { word: "Resource", translation: "Recurso" },
    { word: "Response", translation: "Resposta" },
    { word: "Restore", translation: "Restaurar" },
    { word: "Root", translation: "Raiz (Admin/Pasta)" },
    { word: "Router", translation: "Roteador" },
    { word: "Runtime", translation: "Tempo de execução" },
    { word: "Scalability", translation: "Escalabilidade" },
    { word: "Scan", translation: "Escanear/Verificar" },
    { word: "Scenario", translation: "Cenário" },
    { word: "Schema", translation: "Esquema (Banco de dados)" },
    { word: "Screen", translation: "Tela" },
    { word: "Script", translation: "Script (Roteiro de código)" },
    { word: "Search", translation: "Busca" },
    { word: "Security", translation: "Segurança" },
    { word: "Server", translation: "Servidor" },
    { word: "Session", translation: "Sessão" },
    { word: "Settings", translation: "Configurações" },
    { word: "Setup", translation: "Instalação/Configuração" },
    { word: "Shortcut", translation: "Atalho" },
    { word: "Site", translation: "Site" },
    { word: "Software", translation: "Software" },
    { word: "Solution", translation: "Solução" },
    { word: "Source Code", translation: "Código Fonte" },
    { word: "Specification", translation: "Especificação" },
    { word: "Speed", translation: "Velocidade" },
    { word: "Sprint", translation: "Sprint (Ciclo Ágil)" },
    { word: "Stack", translation: "Pilha (Estrutura/Tecnologias)" },
    { word: "Standard", translation: "Padrão" },
    { word: "Startup", translation: "Startup/Inicialização" },
    { word: "Status", translation: "Status/Estado" },
    { word: "Storage", translation: "Armazenamento" },
    { word: "Stream", translation: "Fluxo (de dados)" },
    { word: "Structure", translation: "Estrutura" },
    { word: "Support", translation: "Suporte" },
    { word: "Switch", translation: "Switch (Comutador/Troca)" },
    { word: "Syntax", translation: "Sintaxe" },
    { word: "System", translation: "Sistema" },
    { word: "Table", translation: "Tabela" },
    { word: "Tag", translation: "Tag/Etiqueta" },
    { word: "Target", translation: "Alvo" },
    { word: "Task", translation: "Tarefa" },
    { word: "Technology", translation: "Tecnologia" },
    { word: "Template", translation: "Modelo/Template" },
    { word: "Terminal", translation: "Terminal" },
    { word: "Test", translation: "Teste" },
    { word: "Text", translation: "Texto" },
    { word: "Theme", translation: "Tema" },
    { word: "Thread", translation: "Thread (Fio de execução)" },
    { word: "Tool", translation: "Ferramenta" },
    { word: "Traffic", translation: "Tráfego" },
    { word: "Transaction", translation: "Transação" },
    { word: "Transfer", translation: "Transferência" },
    { word: "Trigger", translation: "Gatilho" },
    { word: "Type", translation: "Tipo" },
    { word: "Update", translation: "Atualização" },
    { word: "Upgrade", translation: "Upgrade (Melhoria)" },
    { word: "Upload", translation: "Upload (Enviar)" },
    { word: "URL", translation: "URL (Endereço Web)" },
    { word: "User", translation: "Usuário" },
    { word: "Username", translation: "Nome de usuário" },
    { word: "Utility", translation: "Utilitário" },
    { word: "Validation", translation: "Validação" },
    { word: "Value", translation: "Valor" },
    { word: "Variable", translation: "Variável" },
    { word: "Vector", translation: "Vetor" },
    { word: "Vendor", translation: "Fornecedor" },
    { word: "Version", translation: "Versão" },
    { word: "Video", translation: "Vídeo" },
    { word: "View", translation: "Visualização" },
    { word: "Virtual", translation: "Virtual" },
    { word: "Virus", translation: "Vírus" },
    { word: "Visibility", translation: "Visibilidade" },
    { word: "Volume", translation: "Volume" },
    { word: "VPN", translation: "VPN (Rede Privada)" },
    { word: "Warning", translation: "Aviso" },
    { word: "Web", translation: "Web" },
    { word: "Website", translation: "Site" },
    { word: "Widget", translation: "Widget (Componente)" },
    { word: "Width", translation: "Largura" },
    { word: "Window", translation: "Janela" },
    { word: "Wireless", translation: "Sem fio" },
    { word: "Workflow", translation: "Fluxo de trabalho" },
    { word: "Workstation", translation: "Estação de trabalho" }
];

module.exports = listaCompleta;